site_name: utPLSQL
site_description: utPLSQL Documenation Powerful Unit Testing Framework for Oracle PL/SQL
copyright: Copyright &copy; 2016 - utPLSQL Team
repo_url: https://github.com/utplsql/utplsql/

pages:
  - Home: index.md
  - User Guide:
       - Installation: userguide/install.md
       - Getting Started: userguide/getting-started.md
       - Annotations: userguide/annotations.md
       - Upgrade utPLSQL : userguide/upgrade.md
  - About:
       - Project Details: about/project-details.md
       - License: about/license.md
       - Support: about/support.md
